name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['10', '>=14']

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
